### PR TITLE
Moves ImagePickerActivity's logic into a Fragment

### PR DESCRIPTION
**Pull request by Ruberik**
…called ImagePickerFragment. Keeps the toolbar and menus in the Activity.

This also adds a custom Activity to the sample app that is very similar to ImagePickerActivity, but includes a larger-sized preview.

Replaces #164, which I sort-of-accidentally squished due to some Git challenges.

### CODE REVIEW

**Comment by idish** [comment]
Will this be merged anytime soon?

**Comment by Ruberik** [comment]
I would very much like for this to be merged. I just rebased onto main. @esafirm, I would have preferred to do the AndroidX conversion after this PR. Even though it's an automatic process, it required a bunch of manual editing for me to get it right in the rebase.

**Comment by esafirm** [comment]
Hi @Ruberik sorry for the inconvenient about AndroidX and thanks for this PR. 
This is really great PR, hope you don't mind i'm adding some commits to it.

Really love how the Custom UI sample works! 
Thanks for your contribution let's merge this 🎉

**Comment by esafirm** [comment]
Also let's bump the version to 2.0! 🎉🎉🎉

**Comment by Ruberik** [comment]
Thanks for merging, @esafirm!

**Pull request merged**
