### PR TITLE
Moves ImagePickerActivity's logic into a Fragment

### PR DESCRIPTION
**Pull request by Ruberik**
…called ImagePickerFragment. Keeps the toolbar and menus in the Activity.

This also adds a custom Activity to the sample app that is very similar to ImagePickerActivity, but includes a larger-sized preview.

For review purposes, I suggest diffing the old ImagePickerActivity.java against the new ImagePickerActivity.java, and against the new ImagePickerFragment.java. Example commandline:

git diff ~/dev/android-image-picker-head/imagepicker/src/main/java/com/esafirm/imagepicker/features/ImagePickerActivity.java ./ImagePickerFragment.java

### CODE REVIEW

**Comment by Ruberik** [comment]
A few notes:

1. I welcome feedback and proposed changes. I'm hoping that this can eventually end up becoming part of the repository, and I'm willing to do some extra work so that happens.

2. Regarding your View idea: I think it's probably feasible, but I don't know that it's better. I imagine that this is a useful halfway step in any case, so we can resume the conversation from here. I don't think you want to pull this change if you plan to switch to a View later, though; you'd end up having to keep the Fragment around for backwards-compatibility.

3. ImagePickerActivity still implements ImagePickerView, even though ImagePickerFragment is the thing that _really_ does all that work (and now also implements it). I only kept it because the interface methods are public, and I guess someone might be calling them.

**Comment by esafirm** [comment]
Woah, this is cool. Will take some times to review and test though. 🙏

**Comment by Ruberik** [comment]
Thanks, Esa. Bear in mind that I'm not an expert on Activities and Fragments, so I might have missed something: I almost missed a problem where denying permissions would simply ask for permission again. It's worth a close look.

**Comment by esafirm** [comment]
@Ruberik will do. Can you please rebase the PR with the current master. I just setup some CI on the repo so we know the build status more easily 😄

**Comment by Ruberik** [comment]
I have feared this day for some time: the day when I would have to learn about Git.

I think I've sorted it out, but I messed up a bit on the way. Opening a new PR with this same stuff in it.

**Pull request closed without merging**
