### PR TITLE
Support picking photos from the external storages like Google Photos, Dropbox etc

### PR DESCRIPTION
**Pull request by india2sarthak**
Allows users to pick photos from external shared storage such as
Google Photos, Dropbox, etc

**Demo** 

https://user-images.githubusercontent.com/28748775/153799081-427acb8e-c0f0-4332-911a-110bc41e966a.mp4

### CODE REVIEW

**Comment by india2sarthak** [comment]
Anyone looking to use it can do so by using the following gradle ` implementation 'com.github.india2sarthak:android-image-picker:main-SNAPSHOT'`

**Comment by mikemike396** [comment]
This is awesome! Great job!

**Comment by esafirm** [comment]
Hi @india2sarthak this is really nice. While I'm mostly not active In this project, I would like getting this merged to the project. 

One thing missing is the feature flag. Could you add it to the configuration so people can choose the behavior.

Thank you

**Comment by esafirm** [comment]
Have some time this weekend, will try to merge this.

I plan to make this toggleable between
```
1. None
2. Icon in the title bar
3. First tile in the picker
```
As the last tile in the image picker will result in a lot of scrolling if a user has a lot of images.

WDYT?

**Comment by esafirm** [comment]
After starting implementation, I realized there are multiple things to handle first.

1. Compliance in mode: current implementation only cover `SINGLE_MODE`, not multiple selections. We may need to download the source is from external 
2. Feature flag, as mentioned above
3. Config check: we want to make the config throw error if condition is not possible

**Comment by india2sarthak** [comment]
@esafirm  Really appreciate you picking this, been really busy with other stuff and hence have not been able to pick this. Wrt to the config modes (None, Icon, First tile). Not so sure about it being in the first position as users might want to give a preference to their local photos before looking into the external sources. Or could have both (Depending on the config)?

**Pull request closed without merging**
