### PR TITLE
fix deprecated pickCamera

### PR DESCRIPTION
**Pull request by chihung93**
Removed onActivityResult which is deprecated

### CODE REVIEW

**Comment by chihung93** [comment]
@esafirm  Please help me review it

**Comment by esafirm** [comment]
Hey @chihung93 this looks good except for the nitty formatting. Could you please take a look? Thanks.

**Comment by chihung93** [comment]
> 
Hi @esafirm , What do you mean the nitty formatting?
I assume that its a reformatted code, so I have do that on this PR https://github.com/esafirm/android-image-picker/pull/417

Thanks.

**Comment by esafirm** [comment]
It's all good. Already push the formatting commit myself and merge the PR

**Pull request merged**
