### PR TITLE
Fixes #44, Modify to use thumbnail in gif format images.

### LINKED ISSUE #44: GIF images are too late in image picker.
In image picker, gif format images are too late.
I use glide lib.

I think it's because of the disk cache. In glide lib, diskCacheStrategy.SOURCE or NONE is need to speed up for gif format.

### PR DESCRIPTION
**Pull request by xpdlf1004**
Because this project is using glide and glide disk cache, gif format is too slow to be loaded.

### CODE REVIEW

**Comment by esafirm** [comment]
@xpdlf1004 there's another unrelated commits for this pull request `586ff11`, `7be53e3`

I think the better solution for this issue is to give developer a choice of Image loading and item drawing implementation.

**Comment by esafirm** [comment]
@xpdlf1004 I've added custom image loader support and gif indicator in this 
https://github.com/esafirm/android-image-picker/releases/tag/1.6.0-beta

Can you try it? cc: @Rainer-Lang

**Comment by xpdlf1004** [comment]
@esafirm :D Good !!
How can I use my custom image loader?
There is no setImageLoader function.

**Comment by esafirm** [comment]
@xpdlf1004 Silly me! 
Just fix that and add sample in here https://github.com/esafirm/android-image-picker/releases/tag/1.6.0-beta2

You can also check the `imageloader` branch.

**Comment by xpdlf1004** [comment]
@esafirm Thank you !~ It looks good.

**Comment by xpdlf1004** [comment]
@esafirm 
Crash on my project. (I used version 1.6.0b)

```
ImagePicker.create(this).imageLoader(new ImageLoader() {
    @Override
    public void loadImage(String path, ImageView imageView, ImageType imageType) {
        Glide.with(imageView.getContext()).load(path).asBitmap().placeholder(imageType == ImageType.FOLDER? R.drawable.ic_empty_image: R.drawable.ic_empty_image).error(imageType == ImageType.FOLDER? R.drawable.ic_empty_image: R.drawable.ic_empty_image).into(imageView);
        }
    }).folderMode(true).theme(R.style.AppTheme).multi().imageDirectory("Campuspick").limit(20 - attachDataList.size()).start(SELECT_FILE);

```

This is error log
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.vinulabs.campuspick, PID: 31734
                  java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.vinulabs.campuspick.ui.ArticleWriteActivity$3)
                      at android.os.Parcel.writeSerializable(Parcel.java:1536)
                      at com.esafirm.imagepicker.features.ImagePickerConfig.writeToParcel(ImagePickerConfig.java:155)
                      at android.os.Parcel.writeParcelable(Parcel.java:1505)
                      at android.os.Parcel.writeValue(Parcel.java:1411)
                      at android.os.Parcel.writeArrayMapInternal(Parcel.java:733)
                      at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
                      at android.os.Bundle.writeToParcel(Bundle.java:1133)
                      at android.os.Parcel.writeBundle(Parcel.java:773)
                      at android.content.Intent.writeToParcel(Intent.java:9206)
                      at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3494)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1526)
                      at android.app.Activity.startActivityForResult(Activity.java:4389)
                      at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
                      at android.app.Activity.startActivityForResult(Activity.java:4348)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                      at com.esafirm.imagepicker.features.ImagePicker$ImagePickerWithActivity.start(ImagePicker.java:40)
                      at com.vinulabs.campuspick.ui.ArticleWriteActivity.selectImage(ArticleWriteActivity.java:247)
                      at com.vinulabs.campuspick.ui.ArticleWriteActivity.onPhotoClicked(ArticleWriteActivity.java:257)
                      at com.vinulabs.campuspick.ui.ArticleWriteActivity$$ViewInjector$2.doClick(ArticleWriteActivity$$ViewInjector.java:41)
                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                      at android.view.View.performClick(View.java:6213)
                      at android.view.View$PerformClick.run(View.java:23645)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6646)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                   Caused by: java.io.NotSerializableException: com.vinulabs.campuspick.ui.ArticleWriteActivity
                      at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
                      at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
                      at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
                      at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
                      at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
                      at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
                      at android.os.Parcel.writeSerializable(Parcel.java:1531)
                      at com.esafirm.imagepicker.features.ImagePickerConfig.writeToParcel(ImagePickerConfig.java:155) 
                      at android.os.Parcel.writeParcelable(Parcel.java:1505) 
                      at android.os.Parcel.writeValue(Parcel.java:1411) 
                      at android.os.Parcel.writeArrayMapInternal(Parcel.java:733) 
                      at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408) 
                      at android.os.Bundle.writeToParcel(Bundle.java:1133) 
                      at android.os.Parcel.writeBundle(Parcel.java:773) 
                      at android.content.Intent.writeToParcel(Intent.java:9206) 
                      at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3494) 
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1526) 
                      at android.app.Activity.startActivityForResult(Activity.java:4389) 
                      at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48) 
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77) 
                      at android.app.Activity.startActivityForResult(Activity.java:4348) 
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859) 
                      at com.esafirm.imagepicker.features.ImagePicker$ImagePickerWithActivity.start(ImagePicker.java:40) 
                      at com.vinulabs.campuspick.ui.ArticleWriteActivity.selectImage(ArticleWriteActivity.java:247) 
                      at com.vinulabs.campuspick.ui.ArticleWriteActivity.onPhotoClicked(ArticleWriteActivity.java:257) 
                      at com.vinulabs.campuspick.ui.ArticleWriteActivity$$ViewInjector$2.doClick(ArticleWriteActivity$$ViewInjector.java:41) 
                      at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
                      at android.view.View.performClick(View.java:6213) 
                      at android.view.View$PerformClick.run(View.java:23645) 
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6646) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

**Comment by esafirm** [comment]
@xpdlf1004 due to ImageLoader is serialized, you can't use anonymous inner class for `imageLoader`

Kindly check the sample project. Will update the readme soon!

**Pull request closed without merging**
