### PR TITLE
Add spanish and catalan translations

### PR DESCRIPTION
**Pull request by pballart**
Adds translations for spanish and catalan languages

### CODE REVIEW

**Comment by pballart** [comment]
Hello @esafirm could you take a look at this PR?

**Comment by Zookey** [comment]
@esafirm Can you approve this PR? I need this translation in my app and Spanish is very common language so people could benefit from this PR. 

cc @pballart

**Comment by esafirm** [comment]
Sure @pballart @Zookey
Merging this. Thanks for the PR

**Comment by pballart** [comment]
Hello @esafirm thanks for merging it. Can we get a new release with those changes? Thank you!

**Comment by Zookey** [comment]
@esafirm Is there a plan to release this? Thanks.

**Pull request merged**
