### PR TITLE
Show the video duration on the image picker.

### PR DESCRIPTION
**Pull request by xpdlf1004**
- Show the duration label as HH:mm:ss or mm:ss format.

https://github.com/esafirm/android-image-picker/issues/270

### CODE REVIEW

**Comment by esafirm** [comment]
@xpdlf1004 since this is not cached, how's the performance of retrieving metadata?

**Comment by xpdlf1004** [comment]
> @xpdlf1004 since this is not cached, how's the performance of retrieving metadata?

How about use the member variable on ImagePickerAdapter that is caching the video duration?
like HashMap<url, duration>()

**Comment by xpdlf1004** [comment]
> @xpdlf1004 since this is not cached, how's the performance of retrieving metadata?

Please, check it again. :)

**Comment by xpdlf1004** [comment]
@esafirm ping ~ 3

**Comment by esafirm** [comment]
@xpdlf1004 hi sorry for the wait, this is great 👍

**Comment by Jatindersyall12** [comment]
@esafirm I am unable see video.Video is shown in gray color ..

**Comment by Jatindersyall12** [comment]
Video thumbnail is not shown

**Pull request merged**
